export let products = [
  {
    id: "1",
    nombre: "Router AX1800 Linksys",
    descripcion:
      "El Router AX1800 Linksys es una opción ideal para aquellos que buscan una conexión rápida y segura en su hogar.",
    precio: 100,
    imagenn: { src: "", alt: "Product 1" },
    category: "routers",
    cantidad: 10,
  },
  {
    id: "2",
    nombre: "Product 2",
    descripcion: "descripcion of Product 2",
    precio: 200,
    imagen: { src: "", alt: "Product 2" },
    category: "respaldos",
    stock: 20,
  },
  {
    id: "3",
    nombre: "Product 3",
    descripcion: "descripcion of Product 3",
    precio: 300,
    imagen: { src: "", alt: "Product 3" },
    category: "instalaciones",
    stock: 30,
  },
  {
    id: "4",
    nombre: "Product 4",
    descripcion: "descripcion of Product 4",
    precio: 400,
    imagen: { src: "", alt: "Product 4" },
    category: "computadoras",
    stock: 40,
  },
  {
    id: "5",
    nombre: "Product 5",
    descripcion: "descripcion of Product 5",
    precio: 500,
    imagen: { src: "", alt: "Product 5" },
    category: "routers",
    stock: 50,
  },
];
